name: Preview web in Vercel

on:
  workflow_dispatch:
    inputs:
      base:
        required: true
        type: string
      head:
        required: true
        type: string

jobs:
  preview-in-vercel:
    name: Preview web in Vercel
    runs-on: ubuntu-latest
    environment: actions
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
